return {
  -- {
  --   "princejoogie/dir-telescope.nvim",
  --   dependencies = {
  --     "nvim-telescope/telescope.nvim",
  --   },
  --   config = function()
  --     require("dir-telescope").setup({
  --       -- these are the default options set
  --       hidden = true,
  --       no_ignore = false,
  --       show_preview = true,
  --     })
  --
  --     require("telescope").load_extension("dir")
  --   end,
  -- },
  -- {
  --   "nvim-telescope/telescope.nvim",
  --   dependencies = {
  --     {
  --         "nvim-telescope/telescope-live-grep-args.nvim" ,
  --         -- This will not install any breaking changes.
  --         -- For major updates, this must be adjusted manually.
  --         version = "^1.0.0",
  --     },
  --   },
  --   config = function()
  --     local telescope = require("telescope")
  --     local lga_actions = require("telescope-live-grep-args.actions")
  --
  --     telescope.setup {
  --       extensions = {
  --         live_grep_args = {
  --           auto_quoting = true,
  --           mappings = {
  --             i = {
  --               ["<C-k>"] = lga_actions.quote_prompt(),
  --               ["<C-i>"] = lga_actions.quote_prompt({ postfix = " --iglob " }),
  --             },
  --           },
  --         }
  --       }
  --     }
  --
  --     -- then load the extension
  --     telescope.load_extension("live_grep_args")
  --   end
  -- }
}
